Publish/game
2023-chambit-project/KOOSMOOS pull request #25
Opened 2023-08-25 03:34 UTC by TransparentDeveloper

## 이슈 번호
#24

## 작업 분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 기타

## 작업 상세 내용
- 게임 메인 페이지 구성하였습니다.
- public>assets>img 폴더 아래, 해당 페이지에서 사용될 svg 파일 두 개 두었습니다.
- pages>Game 폴더 아래, 해당 페이지에서 사용될 상수값을 관리하는 constants 폴더 와 sub component 를 관리하는 components 폴더를 두었습니다.

## 다음 할 일
- 세부 게임 페이지 작성

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**
- 사용될 텍스트를 관리하는 constants 폴더를 만들었는데., src 바로 아래에도 constants 폴더가 있어서요, 합치는게 나을까요? 
- GameMainPage, index 파일에 비슷한 구조의 코드가 두번 반복됩니다. 반복문 등으로 코드를 줄일 수 있는데., 안읽힐까봐 일단은 커밋했습니다. 반복되는 건 줄이는 게 더 좋을까요?

🔴 **이건 반드시 확인해 주세요!**

2023-08-25 03:34 UTC, TransparentDeveloper commented
아 결과물 동영상 깜박했습니다. 바로 올리겠습니다.!

2023-08-25 03:49 UTC, TransparentDeveloper commented
![좌우 화면에 hover 시](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/6e9190f4-019a-4e9a-8a72-a8f1ba6bb7b5)

![button hover](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/bcc89c00-543e-468d-845c-fe8228f28724)

2023-08-25 13:47 UTC, Doeunnkimm requested changes
확인하고 리뷰 남깁니다 :)

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +import * as C from '../../constants/index'
src 하위에 있는 constants 폴더에서 관리해 주시면 될 거 같아요.

그리고 constant 폴더에 있는 index.ts에 잊지말고 export 해서 사용해주세요!

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +export const Modal: FC<Props> = ({ align }) => {
Modal이라는 컴포넌트 명이 좀 명확하지 못한 것 같습니다🤔
해당 컴포넌트는 일반적인 Modal은 아니니까요!?

좀 더 명확한 컴포넌트명으로 변경해주세요!

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +      <S.MainHeading>{align === 'left' ? C.MainHeading.left : C.MainHeading.right}</S.MainHeading>
삼항 연산자 사용하지 않아도 됩니다! 리팩터링을 해보세용

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +        bgColor={align === 'left' ? '#CCA148' : '#1562AF'}
여기도 마찬가지이긴 한데, 개인적으로 컬러를 하드코딩하는 걸 그렇게 좋아하진 않기도 합니다..!! 그래서 위에 제가 리뷰 남긴 것 처럼 객체화 하셔서 불러오시는 게 좋을 거 같아요!

혹시 제가 theme.COLOR에 피그마에 기재되어 있는 컬러를 모두 삽입해 두긴 했는데 한번 찾아보세요!

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +        bgColor={align === 'left' ? '#CCA148' : '#1562AF'}
아 그리고 지금 보니까 계속 `align` 하나에 대해 계속 값을 가져가고 있으니

```ts
const alignToGameItem = {
  left: {
    headingText: 'adsf',
    bgColor: 'adf'
  },
  right: { ... }
} as const
```

이런 식으로 한번에 모두 관리하는 게 좋아보이네요!

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/index.tsx
> +        <Modal align="left"></Modal>
태그 사이에 아무런 요소가 없다면 단일 태그로 닫으셔도 됩니다~!

```suggestion
        <Modal align="left" />
```

2023-08-25 13:47 UTC, Doeunnkimm commented on src/pages/Game/index.tsx
> +      </S.HalfBox>
한번더 추상화 해서 align만 넘겨도 처리될 수 있도록 해보세요!

2023-08-26 03:19 UTC, TransparentDeveloper commented on src/pages/Game/components/Modal/index.tsx
> +import * as C from '../../constants/index'
[chore: constants 관리 파일 변경](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/bbf16ef472742cf090e280c3d903b5af5b33adef)

넵 src>constants>gameItem.ts 파일 만들어서 필요한 값 적어두었습니다. GamePage 관련해서 앞으로도 이 파일에 정리하겠습니다.

2023-08-26 03:21 UTC, TransparentDeveloper commented on src/pages/Game/components/Modal/index.tsx
> +export const Modal: FC<Props> = ({ align }) => {
[chore: 컴포넌트 이름 변경 (Modal -> ColorPalette)](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/d114752aea5f6c5a774abfb4870cc36fb7fb9e92)

Modal 에서 ColorPalette 로 변경했는데, 의미가 명확히 담긴지는 모르겠네요..

2023-08-26 03:22 UTC, TransparentDeveloper commented on src/pages/Game/components/Modal/index.tsx
> +      <S.MainHeading>{align === 'left' ? C.MainHeading.left : C.MainHeading.right}</S.MainHeading>
[refactor: 삼항연산자 제거 & 속성값으로 좌우 UI 구분](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/2d444390ce6fbf034af28a0d27ef167e3fb393d1)

어떤 말씀하셨는지 이해했습니다. 확실히 전보다 깔끔해진거 같아요.!

2023-08-26 03:23 UTC, TransparentDeveloper commented on src/pages/Game/components/Modal/index.tsx
> +        bgColor={align === 'left' ? '#CCA148' : '#1562AF'}
[chore: constants 관리 파일 변경](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/bbf16ef472742cf090e280c3d903b5af5b33adef)

말씀하신대로 구조를 짜니까 전달할때 속성값으로 값을 빼내기 쉬워졌어요 bb

2023-08-26 03:24 UTC, TransparentDeveloper commented on src/pages/Game/index.tsx
> +        <Modal align="left"></Modal>
전에도 지적 한번 주셨죠 ㅋㅋ 알고는 있는데, 자동완성이 되버려서 자꾸 놓치네요., 잘 살펴볼께요~

2023-08-26 03:26 UTC, TransparentDeveloper commented on src/pages/Game/index.tsx
> +      </S.HalfBox>
[refactor: 반복되는 코드 component 화](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/1a07caf4071e475f5f2ae4337b3df0d8f59b29a3)

수정을 해봤는데, 어떤가요?? index 파일이 간결해지긴 했습니다.

2023-08-26 03:37 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +      <S.MainHeading>{align === 'left' ? C.MainHeading.left : C.MainHeading.right}</S.MainHeading>
오 역시 윤신님 제가 무슨 의도로 말씀드렸는지 바로 파악하시는군요...👍..따봉

2023-08-26 03:39 UTC, Doeunnkimm commented on src/pages/Game/index.tsx
> +      </S.HalfBox>
`ColorPallete`는 왜 따로 빼두셨는지 의도하신 바가 궁금합니다!

2023-08-26 03:41 UTC, Doeunnkimm commented on src/pages/Game/components/Modal/index.tsx
> +export const Modal: FC<Props> = ({ align }) => {
음~ Side에서 열리는 컴포넌트이니까 SideOpenDescription ? 정도도 괜찮을 거 같네요!

2023-08-26 05:11 UTC, TransparentDeveloper commented on src/pages/Game/index.tsx
> +      </S.HalfBox>
음.. 하위 컴포넌트 간 호출이 이뤄지면 추척하기 힘들거 같아서., 가장 상위 index 파일에 모두 명시하려고 했습니다.

2023-08-26 05:32 UTC, TransparentDeveloper commented on src/pages/Game/components/Modal/index.tsx
> +export const Modal: FC<Props> = ({ align }) => {
[chore: 컴포넌트 이름 변경 (ColorPalette -> SideOpenDescription)](https://github.com/2023-chambit-project/KOOSMOOS/pull/25/commits/b1a72ca12a0c74b49dbcc61825ee0472c9e2ecb3)

넵, 감사합니다. 수정 했습니다.

2023-08-26 05:51 UTC, Doeunnkimm commented on src/pages/Game/index.tsx
> +      </S.HalfBox>
넵! 알겠습니다!

2023-08-26 05:51 UTC, Doeunnkimm approved these changes

2023-08-26 05:52 UTC, merged