#3 공용 컴포넌트 중 Button 디자인 수정한 버전을 추가했습니다.
2023-chambit-project/KOOSMOOS pull request #36
Opened 2023-09-25 14:32 UTC by TransparentDeveloper

## 이슈 번호
#3

## 작업 분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 기타

## 작업 상세 내용
- Button2 컴포넌트 작성
- props 정의
  - `icon` : 아이콘 데이터
  - `variant : { "default" | "outlined" }` : 버튼의 외곽선 여부
  - `size : { "default" | "fit" | "full" }` : 버튼의 크기
  - `round : { "default" | "slightly" | "very" }` : 둥긂 정도
  - `skin : { "default" | "light" }` : 폰트, 아이콘, 외곽선 색상
  - `idleBgColor : string` : 버튼의 기본 배경 색상
  - `hoverBgColor : string` : 호버 시 버튼의 배경 색상

## 다음 할 일

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**

🔴 **이건 반드시 확인해 주세요!**
- 기존 Button 컴포넌트를 삭제하지 않았습니다.!
- 기존 Button 과 달리 배경 색상을 마음대로 지정할 수 있습니다.
  + ⚠️ idleBgColor, hoverBgColor 속성 값은 반드시 필요합니다. 
  
  
![ButtonV2](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/5f668e96-b123-45a0-b9fd-56364030ef75)

2023-09-25 14:51 UTC, Doeunnkimm requested changes
리뷰 남겼습니다 :)

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
버튼을 사용할 때마다 color를 기입해 주어야 한다는 점이 좀 불편할 것 같아요.
보통 제일 보편적으로 쓰이는 버튼을 모두 default를 해두고 color를 받고 싶은 경우 bgColor를 받되, hover시에는 알아서 opacity를 주거나 채도를 살짝 높이는 계산을 추가하는 게 나아보입니다.

필요하면 특정 컬러 이상부터는 폰트의 색깔을 검/흰으로 해주는 것도 필요할 것 같긴 합니다.

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  min-height: 40px;
이 속성은 왜 필요한건가요?

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  padding: 0.5rem 1rem;
width와 height를 설정했는데 padding도 속성을 넣어주신 이유가 궁금합니다~

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  margin: 0.5rem;
margin 같은 **컴포넌트 밖의 속성들**은 사용하는 컴포넌트에서 속성을 주는 것이 좋습니다.

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +    border: none;
원래 outline이 있었으면 보통 hover해도 outline은 그대로인 경우가 많은 것 같아요.

2023-09-25 14:51 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +}
border-radius는 px로 하셔도 돼요! 
참고로, 저희 defulat를 8px입니다! 그리고 very 저 프로퍼티는 혹시 의도가 완전 말린 border였다면 50%로 하셔도 됩니다~!

2023-09-25 15:11 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
그 고민을 되게 오래했는데, string 으로  넘어온 bgColor 에 대해서 apla 값을 부여하는 게 어렵더라구요. opacity를 조절하자니 버튼 위의 text/ icon 도 같이 영향을 받고,,

색 조합을 미리 만드는 방법으로 고민해보겠습니다.

2023-09-25 15:11 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  padding: 0.5rem 1rem;
size = 'fit' 인 경우에 border 에 text가 붙을 수 있어서 사용했습니다. 해당 경우에만 쓰이도록 수정해볼게요.

2023-09-25 15:12 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +}
넵, 수정하겠습니다.!

2023-09-25 15:13 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
유명한 UI 라이브러리의 Button 컴포넌트 코드를 뜯어보시는 것도 도움이 될 것 같네요..!

2023-09-25 15:13 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  min-height: 40px;
아 아뇨 저는 min-height만 여쭤본겁니다..

2023-09-25 16:15 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
- [chore: 버튼 hover 상태 시, 그림자 효과 부여](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/41cd877c28dbc10b0caa0528b3918a6cc13f162d)

material-ui 참고하여, 호버 상태에서는 버튼 내외부로 그림자 효과만 부여했습니다. 단 하나의 배경 색상만 외부에서 입력하도록 했고, 전달받지 않을 경우에 기본색상 지정하였습니다.

참고: https://mui.com/material-ui/react-button/

2023-09-25 16:16 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  min-height: 40px;
- [chore: min-height 속성 제거](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/1021fd32264fbc9a1b2642f97a8f749840c6ca4b)

해당 속성 없이도 별 문제 없는걸로 확인했고 제거하였습니다. :)

2023-09-25 16:23 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  padding: 0.5rem 1rem;
- [chore: props>size 값이 'fit' 일 경우, padding 속성 부여](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/94dbd4c4ebb1c50c24e143cd8bb8cf1e0f9f4fd6)

수정했습니다. 잘 적용되네요.
<img width="1029" alt="스크린샷 2023-09-26 오전 1 20 43" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/2a93d0b8-efcd-491d-8efb-3cb653f5cafb">

2023-09-25 16:23 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +  margin: 0.5rem;
- [chore: margin 속성 제외](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/9aca2ef1b6a20e768ac5daededb24365c946475a)

제거했습니다.!

2023-09-25 16:24 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +    border: none;
- [chore: 버튼 hover 상태 시, 그림자 효과 부여](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/41cd877c28dbc10b0caa0528b3918a6cc13f162d)

이젠 outline이 호버상태에서도 유지됩니다.

2023-09-25 16:25 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.styles.ts
> +}
- [chore: roundCSS 단위 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/8f13538c0764d9e46a2bc54ded5e31e5b67f549e)

넵 잘 적용되었습니다.!

<img width="952" alt="스크린샷 2023-09-26 오전 1 21 44" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/9832bf09-fe92-4ef8-a17f-e3ebe070cf25">

2023-09-27 02:00 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.types.ts
> +  idleBgColor?: string
bgColor로 해도 충분히 의미전달 될 것 같아요 👍

2023-09-27 02:00 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
혹시 적용된 모습 보여주실 수 있나요 ?

2023-09-27 06:27 UTC, Doeunnkimm commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
적용된 거 보여주실 수 있나요 ?

2023-09-27 13:28 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
<비교1>

- 영상
![button1](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/dc7ec10c-7ba1-4294-9cd5-116a6a9dae92)

- 코드
<img width="573" alt="스크린샷 2023-09-27 오후 10 22 02" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/f2cc30f6-3b02-4b04-a015-73dfea20fcd4">

2023-09-27 13:29 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
<비교2>

- 영상
![button2](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/1e5177e5-a1da-48e3-b2ad-2d4f8200289c)


- 코드
<img width="667" alt="스크린샷 2023-09-27 오후 10 22 08" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/c479a596-77e7-40ae-82ca-539c9ec92e69">

2023-09-27 13:29 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
효과가 약하네요;; 수정하겠습니다.

2023-09-27 13:30 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  idleBgColor?: string
- [chore: type 값 이름 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/5032665b3ebe06e086c9e82319a9ddd68c6279be)

넵 수정했습니다.!

2023-09-27 14:01 UTC, TransparentDeveloper commented on src/components/ButtonV2/ButtonV2.types.ts
> +  hoverBgColor: string
- [chore: 호버 상태 시, 그림자 효과 제거](https://github.com/2023-chambit-project/KOOSMOOS/pull/36/commits/b2cbe435a2e47eac6b3597844a9e61b6b6df1e25)

그림자 효과 제거하고, 다시 배경 색상 변경하도록 수정했습니다. 글자 잘보이도록 text 색상이랑 대비되는 백/흑 색으로만 배경색 주었습니다.

<비교1>

- 영상
![video-1 (1)](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/0503cdd8-cf5c-47be-9a0c-7ccc832fec5a)



- 코드
<img width="651" alt="img-1" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/bab43d8e-8230-4e6d-9c31-38de327e9c2e">

<비교2>

- 영상

![video-2 (1)](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/621e1ade-b079-4780-809b-b36a6c390394)

- 코드
<img width="689" alt="img-2" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/58491d78-8406-4d61-9fce-79113eb68dd4">

2023-09-28 01:06 UTC, Doeunnkimm approved these changes

2023-09-28 01:06 UTC, merged