#44 Replace Button
2023-chambit-project/KOOSMOOS pull request #45
Opened 2023-12-06 15:15 UTC by TransparentDeveloper

## 이슈 번호

- #44

## 작업 분류

- [ ] 버그 수정
- [ ] 신규 기능
- [x] 프로젝트 구조 변경
- [ ] 기타

## 작업 상세 내용

### - 공용 컴포넌트에서 기존 `Button` 이 적용된 타 컴포넌트 를 찾아 `ButtonV2` 로 대체 했습니다. 

1. Header 

  <img width="1430" alt="Header" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/2781b7c8-6ca0-4a76-89a9-f00396a9bd81">

2. GameMain

  <img width="443" alt="GameMain" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/54a4fa25-62b3-43e6-b90f-34c6d47dbf24">

<br/>
<br/>
<br/>
<br/>

### - 기존 `Button` 컴포넌트는 삭제하고, `ButtonV2` 컴포넌트명을 `Button` 으로 수정했습니다.

<br/>
<br/>
<br/>
<br/>

## 다음 할 일

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**

🔴 **이건 반드시 확인해 주세요!**
- 아직 merge 되지 않은 Gallery, Game1 에서 `ButtonV2` 사용하고 있다면, `Button` 으로 수정해야합니다.

2023-12-09 15:19 UTC, Doeunnkimm requested changes
꼭 답변 및 수정 부탁드립니다 ~!

2023-12-09 15:19 UTC, Doeunnkimm commented on src/components/Button/Button.styles.ts
> +    width: 17rem;
default를 고정적으로 size를 정해두셔서 아래와 같이 텍스트가 길게 바로 쓰고 싶어도 size='fit'을 해줘야 하는 불편함이 있는 것 같아요.

<img width="205" alt="image" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/112946860/3a42def8-246b-4b14-840c-393ca347b32f">

2023-12-09 15:19 UTC, Doeunnkimm commented on src/components/Button/Button.styles.ts
> +}
요건 무슨 기준으로 지정하신 건지 여쭤봐도 될까요?

2023-12-09 15:19 UTC, Doeunnkimm commented on src/components/Button/index.tsx
> +import { FC, HTMLAttributes, PropsWithChildren } from 'react'
type 키워드 빠진 거 같아요~

2023-12-09 15:19 UTC, Doeunnkimm commented on src/components/Button/index.tsx
> +    <S.ButtonV2 {...props}>
그냥 Button으로 되어도 될 거 같아요~ 스타일 코드에서 해당 이름 변경하고 여기도 맞춰주세요~!

2023-12-09 15:38 UTC, TransparentDeveloper commented on src/components/Button/index.tsx
> +    <S.ButtonV2 {...props}>
- [chore: 스타일 컴포넌트 이름 변경](https://github.com/2023-chambit-project/KOOSMOOS/pull/45/commits/815da49c1750842574e2aaf37ef2acb3864e1673)

2023-12-09 15:39 UTC, TransparentDeveloper commented on src/components/Button/index.tsx
> +import { FC, HTMLAttributes, PropsWithChildren } from 'react'
[chore: type 키워드 추가](https://github.com/2023-chambit-project/KOOSMOOS/pull/45/commits/112f4843aa93a7a912b04999e408b3b958050e2c)

키워드 추가했습니다.

2023-12-09 15:43 UTC, TransparentDeveloper commented on src/components/Button/Button.styles.ts
> +    width: 17rem;
- [chore: 내부 요소의 크기에 따라 유동적으로 변화되도록 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/45/commits/897db611d97bae35ee29385e5ef1d43ce5e7cbca)

min-width 속성으로 변경해서 해결했습니다.

<기본크기>
<img width="1454" alt="스크린샷 2023-12-10 오전 12 40 39" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/e818213f-06ac-4fdc-9aa4-eb04c4c69fab">

<텍스트가 길어진 경우>
<img width="1454" alt="스크린샷 2023-12-10 오전 12 41 54" src="https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/77c6d783-edd3-4f04-bca4-d04448110ca7">

2023-12-09 15:59 UTC, TransparentDeveloper commented on src/components/Button/Button.styles.ts
> +}
새로 만든 버튼 컴포넌트는 bgColor(배경색) 속성값을 외부에서 주입해서 사용합니다.
버튼을 사용할 개발자들이 하얀 배경을 줄 수도 있고 검은 배경을 줄 수도 있어서, color(폰트 색상 등), hover 시 변화되는 색상 을 미리 지정하기 어렵더라구요. 
(예를 들어, <Button bgColor='white'> 를 했는데, color 도 white 값으로 설정되어 있으면 텍스트가 보이지 않을 것을 걱정했습니다..)

그래서 개발자가 배경 색상을 부여할 때, 그것과 어울리는 폰트 색상을 (검은색과 하얀색 중 하나) 선택할 수 있도록 한 것입니다.
마찬가지로 마우스 호버 를 감지하였을 때, 검은색과 하얀색으로 표시해 줄 수 있도록 했습니다.

실제로 사용한 예시입니다. 

<시연영상>

https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/12d095a3-a43f-498f-bcca-2e571d809dc5

<사용코드>
```js
<Button onClick={onClickSubmitBtn} size="full" bgColor={theme.PALETTE.orange[100]} round="very">
        달로 전송하기.. 🚀
 </Button>
```

bgColor 값으로 주황색 계열을 주었을 때, 그와 어울릴 수 있는 폰트 색상을 하얀색(호버시에는 반전)으로 주고 호버 시 배경색상은 하얀색이되도록 의도했습니다.

2023-12-09 16:04 UTC, Doeunnkimm commented on src/components/Button/Button.styles.ts
> +}
약간 저는 흰색/검정색 이렇게 되는게 뭔가 이질적이다? 느낌이 들어서 여쭤봤던 겁니당
그럼 혹시 hover했을 때 색깔을 지정할 수 있도록 코드 추가해주실 수 있나여

2023-12-10 00:54 UTC, TransparentDeveloper commented on src/components/Button/Button.styles.ts
> +}
넵 알겠습니다~

2023-12-10 01:18 UTC, TransparentDeveloper commented on src/components/Button/Button.styles.ts
> +}
- [chore: 마우스 호버 시, 변경될 색상값을 외부에서 입력받도록 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/45/commits/927a8d0f0caa6135184f755fe372f6812ecf32ca)


기본 속성으로 `theme.COLOR.success` 색상코드 값이 적용되도록 했습니다. 

<br/>
<br/>
<br/>

<default>

https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/8eba9024-81ac-4443-a270-f9ccd589bf3a

```js
 <Button
          icon={faMailForward}
          bgColor="transparent"
          variant="outlined"
          onClick={redirectToGoogleForm}
        >
          우주소식 받기
        </Button>
```

<외부에서 hover 색상 지정>

https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/30b29cba-080d-4bdf-b59c-03c3685283cf

```js
 <Button 
          icon={faMailForward} 
          bgColor="transparent" 
          variant="outlined" 
          onClick={redirectToGoogleForm}>
          우주소식 받기
        </Button>
```

2023-12-10 13:03 UTC, Doeunnkimm commented on src/components/Button/Button.styles.ts
> +}
@TransparentDeveloper success 초록색 아닌가요? default는 어쩔 수 없이 white로 하는 게 제일 나을 거 같긴 합니다.

2023-12-10 16:27 UTC, TransparentDeveloper commented on src/components/Button/Button.styles.ts
> +}
- [chore: hover 시 기본 배경색상, 하얀색으로 변경](https://github.com/2023-chambit-project/KOOSMOOS/pull/45/commits/afa9e509928eafd29b11babee9b511419ef1bc65)

넵 수정했습니다.!

2023-12-11 13:40 UTC, Doeunnkimm commented on src/components/Button/Button.styles.ts
> +}
고생하셨습니다~

2023-12-11 13:40 UTC, merged