갤러리 페이지 - 이미지 로드 시 Skeleton UI 적용
2023-chambit-project/KOOSMOOS pull request #78
Opened 2024-01-29 09:39 UTC by TransparentDeveloper

## 이슈 번호
- #71

## 작업 분류

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 프로젝트 구조 변경
- [ ] 기타

## 작업 상세 내용

- [design: Skeleton Component 작성](https://github.com/2023-chambit-project/KOOSMOOS/commit/49767da505de70cd8e0f7d6a6c18aa82745a9bb4)
  - 다른 리소스 불러올 때도 사용할 수 있도록 공용컴포넌트로 만들어 두었습니다.
  - 로드 중 임을 알릴 텍스트 등이 Skeleton UI 전면에 출력될 수 있도록 하였습니다. 

### 사용예시 👍,  

- _코드_

```js
<Skeleton width="20rem" height="20rem" borderRadius="1rem">
  <div style={{ display: 'flex', flexDirection: 'column', alignContent: 'center', justifyContent: 'center' }}>
    <h1>로딩중</h1>
    <h2>로딩중</h2>
    <h3>로딩중</h3>
  </div>
</Skeleton>
```

- _출력_
<img width='300px' alt='skeleton' src='https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/e7977c6a-a058-496a-acbd-d578f7f26576'>

<br/>

--------------  

<br/>

- [feat: 이미지 로딩 중, Skeleton ui 적용](https://github.com/2023-chambit-project/KOOSMOOS/commit/df575cb7959ca13442d6494de149286619056844)
  - 개별 이미지 별로, 로딩 중인지를 추적하는 상태를 관리합니다.
  - '이미지 로딩중..' 텍스트가 출력합니다.
  
<div align = 'center'>  

![gallery-image-skeleton](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/d6d9723d-052f-420a-a534-08f67069d69d)

</div>
  

## 다음 할 일

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**

🔴 **이건 반드시 확인해 주세요!**

closed #71

2024-01-29 15:06 UTC, Doeunnkimm requested changes
https://velog.io/@tech-hoon/skeleton-ui

위 블로그 참고하셔서 단순한 Skeleton으로 만들어주시면 더 좋을 거 같습니다.... 혹시 어디서 skeleton 에 텍스트 넣은 걸 보시고 텍스트를 넣으신건가요 ......?

2024-02-01 06:26 UTC, TransparentDeveloper commented
- [design: Skeleton Component, 외부에서 컴포넌트 주입되지 않도록 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/20880d1a870e60b908de7a9d431bc9d90a28777f)
  - Skeleton 위에 overlay 되는 것 없이 더 단순하게 수정했습니다.
  
- [feat: SkeletonPicture 전용 Skeleton UI 작성 및 적용](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/e3e8f1e794c9c4413fa6cebf270de265714b6991)
  - `PictureItem.skeleton.tsx` 에는 PictureItem 전용 Skeleton 컴포넌트 작성했습니다.
  - `PictureItem.styles.ts` 파일에 `Skeleton-` 접두어 사용해서 스타일 컴포넌트 만들어두었습니다.

- [feat: Gallery suspense 미적용 & 이미지 로드까지 Skeleton UI 출력](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/3bd6853b2f230048f5cfec17a1635a1b44bc660f)
  -  로켓 로딩 UI 뜨지 않도록 수정했습니다.
  - 이미지까지 완전히 출력될 때까지, Skeleton UI 가 보입니다.

<div align="center">

![skeleton_ui](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/bf493206-1fc8-48f6-b020-82db243cd1b0)

</div>

2024-02-01 06:39 UTC, Doeunnkimm reviewed
@TransparentDeveloper Skeleton 모듈화 방식이 너무 자유도가 높은 거 같고 사용방식이 정리가 안 되어 있는 느낌이 많이 듭니다.

Skeleton 컴포넌트 props으로 w와 h, radius만 받아서 컴포넌트 사용을 통해 스타일을 주입하는 방식만 되어도 이게 더 훨씬 명확할 거 같아요. 스켈레톤 하나 사용하려고 스타일 파일 만들고, import * as S 해서 불러오고 그걸 통해 다시 사용하는 방식이 복잡한 거 같네용

2024-02-01 06:39 UTC, Doeunnkimm commented on src/components/Skeleton/index.tsx
> +}
```suggestion
export const Skeleton: FC<ShapeProps> = ({ ...props }) => {
  return <S.AnimationSkelton {...props} />
}
```

이렇게는 안 되는건가요 ?

2024-02-01 07:35 UTC, Doeunnkimm reviewed
피드백 남겨드린 거 한번 확인 부탁드립니다~

2024-02-01 07:35 UTC, Doeunnkimm commented on src/pages/Gallery/components/PictureList/PictureList.tsx
약간 제 실수가 포함되어 있기도 한데

```tsx
import { useGetNASAImages } from '@/services/queries/gallery'
import { PictureItem } from '..'
import { CATEGORY_MAP } from '../../gallery.constants'
import * as S from './PictureList.styles'
import type { PictureListProps } from './PictureList.types'
import SkeletonPictureItem from '../PictureItem/PictureItem.skeleton'

export const PictureList = ({ onImageClick, selectedCategory }: PictureListProps) => {
  const { data } = useGetNASAImages({ q: CATEGORY_MAP[selectedCategory] })
  const pictures = data?.collection.items

  return (
    <S.PictureListContainer>
      {pictures ? (
        <>
          {pictures?.map((picture, index) => {
            return (
              <S.PictureImageWrapper key={selectedCategory + index}>
                <PictureItem picture={picture} onImageClick={onImageClick}></PictureItem>
              </S.PictureImageWrapper>
            )
          })}
        </>
      ) : (
        Array.from({ length: 10 }).map((_, index) => <SkeletonPictureItem key={index} />)
      )}
    </S.PictureListContainer>
  )
}
```

API 콜을 여기서 하는 게 더 맞는 거 같더라구요. 데이터 받아지기 전에는 Skeleton 10개 보여주는 코드로 작성해봤습니다~
이렇게 하면 `PictureItem` 컴포넌트도 이렇게 될 거 같아요.

```tsx
import type { PictureItemProps } from './PictureItem.types'
import * as S from './PictureItem.styles'

export const PictureItem = ({ picture, onImageClick }: PictureItemProps) => {
  return (
    <S.PictureItemContainer onClick={() => onImageClick(picture.links[0]?.href)}>
      <S.PictureImage src={picture.links[0]?.href} alt={picture.data[0]?.title} />
      <S.PictureName>{picture.data[0]?.title}</S.PictureName>
    </S.PictureItemContainer>
  )
}

```

이외로 PictureItem에서만 사용하는 Skeleton에 Item에서 사용하는 스타일 Wrapper 재사용하면 잘 동작할 겁니다~~
(잘 동작하는 거 확인했습니다.)

가까운 Suspense로 래핑해서 로딩상태로 처리하고 싶었는데 이게 Loading 상태일때가 아니라 undefined일 때를 Skeleton으로 보여줘야 하다보니 View로직에 포함된 거 같아서 아쉽긴 하네요 😓

2024-02-01 08:48 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureItem/PictureItem.styles.ts
> +export const SkeletonPictureItemContainer = styled.div`
무슨 말인지 이해했습니다. 이건 고민 좀 해보겠습니다. 오늘 안으로 수정하겠습니다.

2024-02-01 08:48 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureItem/PictureItem.styles.ts
> +  /** 세 줄 이상 설명시, ... 으로 대체 */
넵 확인했습니다.

2024-02-01 09:24 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureList/PictureList.tsx
> 이외로 PictureItem에서만 사용하는 Skeleton에 Item에서 사용하는 스타일 Wrapper 재사용하면 잘 동작할 겁니다~~ (잘 동작하는 거 확인했습니다.)


이게 무슨 말인지 이해 못했어요
"PictureItem에서만 사용하는 Skeleton에.." => `SkeletonPictureItem` ?
"Item에서 사용하는 스타일 Wrapper.." => `S.PictureImageWrapper` ??

2024-02-02 12:51 UTC, TransparentDeveloper commented
![edit-code-skeleton](https://github.com/2023-chambit-project/KOOSMOOS/assets/50646145/a7a062bb-b1fa-4b5b-8176-786cff903fa0)

- [refactor: SkeletonPictureItem 관련 불필요한 스타일 컴포넌트 제거](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/6372900fb10f8ea2ac8a0f3c8613bad9ed583080)
  - 스타일 컴포넌트 최대한 제거했습니다. 생각을 오래 해봤는데, `position: absolute` 는 필요할 거 같습니다. `PictureItem` 이 랜더 되어야, 이미지를 불러오는 요청이 진행됩니다. (그래서 조건문으로 처리할 수 없었어요;;) `PictureItem` 가 화면 그려지더라도 이미지 가 완전히 불러와질 때까지 skeleton ui 를 보여줘야 해서, `PictureItem` 위에 `SkeletonPictureItem` 가 오버레이 되도록 구현했습니다.
  
- [refactor: useGetNASAImages 사용 위치 변경](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/d8e8c09e233a3673ddca88b0fc006b44c00e7a9b)
  - `useGetNASAImages()` 사용 위치를 `PictureList.tsx` 로 변경했습니다.

2024-02-02 12:57 UTC, Doeunnkimm commented on src/pages/Gallery/components/PictureList/PictureList.tsx
제가 스타일 코드 대강 봤을 때 Item용 Wrapper가 따로 있고 Skeleton용 Wrapper가 따로 있는 걸로 파악되었는데 어차피 둘의 사이즈는 동일하지 않나 해서 말씀드렸어요.

2024-02-05 12:50 UTC, Doeunnkimm reviewed
리뷰 확인 부탁드립니다 🙏

2024-02-05 12:50 UTC, Doeunnkimm commented on src/pages/Gallery/components/PictureItem/PictureItem.tsx
> +          })
이 로직을 여기서 처리해야할 이유가 있을까요? setIsEachImgLoaded, index 모두 다 props으로 받은 걸로 보여서요~
상위에서 아래와 같이 핸들러 만들어서 내리는게 더 가독성에 좋을 거 같아요~

```tsx
const onImgIsLoadedChange = (targetIndex) => {
  setIsEachImgLoaded(prev => prev.map((_, index) => index === targetIndex))
}
```

상위 컴포넌트에서 이 핸들러 만들고, PictureItem의 props으로 `onLoad={() => onImgIsLoadedChange(index)}` 하면 해결할 수 있을 거 같은데 어떠신가요?

2024-02-05 12:50 UTC, Doeunnkimm commented on src/pages/Gallery/components/PictureList/PictureList.tsx
> +    setIsEachImgLoaded(Array(16).fill(false))
지금 api 요청할 때 저희가 16개 사진을 요청했기 때문에 여기서도 16을 사용하신 거 같은데 이 16은 매직넘버 같아요~
constants로 관리하면 유지보수하기 좋을 거 같습니다~

api 쪽에도 상수로 반영해주시면 감사하겠습니다 🙏

2024-02-05 12:50 UTC, Doeunnkimm commented on src/pages/Gallery/components/PictureList/PictureList.tsx
> +          />
전 사실 이전부터 `NASA_IMAGE_BASE`가 굳이 필요할까라는 생각을 많이 했었는데요~!

아예 존재자체 없애버리고 
```suggestion
          {pictures && <PictureItem
            index={index}
            picture={pictures[index]}
            onImageClick={onImageClick}
            setIsEachImgLoaded={setIsEachImgLoaded}
          />}
```
로 해도 동일하게 잘 동작하는 거 같습니다~

2024-02-08 06:36 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureList/PictureList.tsx
> +    setIsEachImgLoaded(Array(16).fill(false))
- [chore: 이미지 호출 갯수 상수화](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/6f19590eeb6b5cef55ad3e171d84d6c82a41426a)
  - `constants>gallery.ts` 에서 관리하도록 했습니다.

2024-02-08 06:37 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureItem/PictureItem.tsx
> +          })
- [refactor: 이미지 로드 상태 변경 관련 props 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/1877d68c6121a3dad493c7df47971446717cac20)
  - 훨씬 좋은 것 같습니다. 👍 참고해서 반영했습니다.,

2024-02-08 06:39 UTC, TransparentDeveloper commented on src/pages/Gallery/components/PictureList/PictureList.tsx
> +          />
- [refactor: 불필요한 상수 제거, 해당 상수에 의존한 코드 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/8e46ea96ae04440a6cdd4d2c2de830700ea14081)
  - 오.. 진심 감탄합니다.. 반영했습니다.!

2024-02-08 06:40 UTC, TransparentDeveloper commented
확인/수정이 늦어서 죄송합니다..
추가적으로 contants 폴더 안에 상수명 모두 대문자로 통일하고, 공백은 '_' 처리해서 이름 형식을 통일 시켰습니다. 
마음에 안드시면 reset 하겠습니다.

- [chore: contants 폴더 내에 상수명 형식 지정 및 적용](https://github.com/2023-chambit-project/KOOSMOOS/pull/78/commits/283663438ababd28b9ff8d87fcaa1908d541d7a5)

2024-02-08 07:10 UTC, Doeunnkimm approved these changes

2024-02-08 07:10 UTC, merged