chore: 갤러리 페이지 내 메뉴바 수정
2023-chambit-project/KOOSMOOS pull request #83
Opened 2024-02-12 04:24 UTC by Doeunnkimm

## 이슈 번호

- #82 

## 작업 분류

- [ ] 버그 수정
- [ ] 신규 기능
- [ ] 프로젝트 구조 변경
- [x] 기타

## 작업 상세 내용

별건 아니고... 갤러리 페이지 내 메뉴바 좀 리모델링 해보았습니다~

https://github.com/2023-chambit-project/KOOSMOOS/assets/112946860/c238d348-f717-408b-bda0-52edeebc27a9

## 다음 할 일

## 체크 리스트
- [x] main 브랜치 pull 받기
- [x] 아직 작업 중인 파일은 올리지 않기

## 질문 사항

💬 **질문이 있어요!**

🔴 **이건 반드시 확인해 주세요!**

2024-02-13 22:00 UTC, TransparentDeveloper requested changes
재밌고 멋진 효과네요. 😁
그래도 좋은 말만하고는 못 보내드립니다.!

2024-02-14 15:49 UTC, Doeunnkimm commented on src/pages/Gallery/components/MenuBar/MenuBar.styles.ts
> +  background-color: rgb(33, 37, 41);
[chore: 스타일 일부 수정](https://github.com/2023-chambit-project/KOOSMOOS/pull/83/commits/06f00d8b29bed2cebed3c1730b83e4509a5689ab)

별 차이없네유 반영했습니다~

2024-02-14 15:49 UTC, Doeunnkimm commented on src/pages/Gallery/components/MenuBar/MenuBar.styles.ts
> +  z-index: 2;
확인 감사합니다~ 반영했어요~

[chore: header의 z-index +1](https://github.com/2023-chambit-project/KOOSMOOS/pull/83/commits/42774502e15c223ed4166d3597b09658a120958a)

2024-02-15 05:21 UTC, TransparentDeveloper approved these changes

2024-02-15 06:48 UTC, merged